### ISSUE TITLE
Remove Jervis Bay from state list for Australian addressing

### ISSUE THREAD

**Issue by digcat** [commerceguys/addressing#160]
Currently when the Australian address offers a state, it includes Jervis Bay, along with the expected NSW, QLD, SA, VIC, WA, TAS, NT and ACT.  Looking at the google feed https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/AU
Currently the sub_keys field is used which includes the Jervis Bay reference.  However there is also "sub_isoids":"ACT~~NSW~NT~QLD~SA~TAS~VIC~WA"

Im unsure whether this should be used along with sub_keys, at the extraction point in script, https://github.com/commerceguys/addressing/blob/65b6faa95dfacfacbf3df448b0283d1eb8434a24/scripts/generate_address_data.php
or as mentioned before on my invalid PR some fix down the line ?

**Comment by bojanz** [comment]
We don't filter by ISO ID because the assumption is that if Google included an entry, it's because it wants it to be displayed. Having an empty ISO ID is not uncommon (not yet assigned, etc). Why don't you ask Google why they consider Jervis Bay to be important enough to include? I am guessing it's because people use it for shipping purposes.
