### ISSUE TITLE
Different type hints between AddressInterface and its Address implementation

### ISSUE THREAD

**Issue by Sylry** [commerceguys/addressing#211]
AddressInterface type hints return getters as `null|string` but Address (which implements the interface) type hints getters as `string`.

Shouldn't it be harmonized?

I can provide a MR, but i'm not sure which one is wanted (`string` or `null|string`) ?

**Comment by bojanz** [comment]
Hi, this is intentional.

Type hints were added (years) after the library was first released, so to give flexibility to implementors, we used wider typehints on the interface than on the sample implementation, which PHP allows. For example, the Drupal integration does not use the Address class, just the interface, and it returns nullable data. But I personally prefer non-nullable data, so the Address object I'm providing in the library does not use null|.

**Comment by Sylry** [comment]
Ok, i understand

Thanks
