### ISSUE TITLE
postal_code_pattern missing from US states since v2.0.0-beta1

### ISSUE THREAD

**Issue by mglaman** [commerceguys/addressing#212]
I was helping an old Laravel project and went to update this library. But our tests started to fail:

```php
        yield 'state with bad zipcode' => ['WI', '13177', [
            'error' => true,
            'message' => '13177 is not a valid postal code for WI.',
            'errorTitle' => 'Validation Error'
        ]];
```

It appears to be due to https://github.com/commerceguys/addressing/commit/516da8b8b949d69380cca20949332a1ba4b7dfcb which removed `postal_code_pattern` for US subdivisions.

We relied on `"postal_code_pattern": "5[34]"`.

\CommerceGuys\Addressing\Validator\Constraints\AddressFormatConstraintValidator::validatePostalCode still supports subdivision postal code patterns.

**Comment by bojanz** [comment]
State-level prefix-based postal code patterns were deprecated in 1.x, that's why 2.x removed them. See #147 for background. There's also https://www.drupal.org/project/address/issues/2828128 for the Drupal-side of the discussion.

We still retain state-level patterns that override the entire country pattern, instead of further refining it.

**Comment by mglaman** [comment]
Ah, bummer. Yeah, I'll just have to write a custom constraint then

**Comment by damienmckenna** [comment]
@mglaman: Did you add something to Commerce to validate US ZIP Codes, or was it custom code for a client project? Am facing this exact request for a client and was surprised that the ZIP Code validation was removed entirely. Thanks.
