### ISSUE TITLE
Using on an active record app

### ISSUE THREAD

**Issue by andrewmclagan** [commerceguys/addressing#25]
Is it possible to implement this package within an active record app / framework?

From my brief look over the codebase, the models seem to be plain php objects... using Doctrine I'm guessing?

thanks!

**Comment by bojanz** [comment]
Yes.

There's nothing Doctrine specific about the models, though Doctrine allows you to reuse those classes simply by defining the field mapping externally.

Active Record is a dirty pattern, so it requires us to do a bit more work, but nothing too bad. You basically implement your own model that implements the library interface.
Let's take Laravel's Eloquent as an example:
```php
class Address extends Model implements AddressInterface {
    protected $table = 'address';
    // Now implement the getters and setters required by the interface.
}
```
Our experience has been that you usually want some kind of a CustomerProfile model above Address that will have related non-address data such as phone, delivery_instructions, etc.

You also need to decide whether you're going to use the AddressFormat and Subdivision objects from the library (thus loading data from the disk), or import the data into the database. There is value in allowing end-users to edit the address formats, so it might make sense to have them in the database. Subdivisions are usually safe to remain on disk, especially since there's 12 thousand of them, making db imports last a while.

**Comment by andrewmclagan** [comment]
Perfect, that was going to be my approach. Absolutely agree with WR being a bit of an anti-pattern. Although one must use what one must use!

**Comment by andrewmclagan** [comment]
I don't really mind having things such as this sitting on the disk as all my servers are SSD anyway.

**Comment by bojanz** [comment]
I won't judge AR lightly, I needed to apply the same approach to the Drupal integration :)
Let me know how the integration is going.
