### ISSUE TITLE
Zone Matcher/Repository missing?

### ISSUE THREAD

**Issue by Casper-O** [commerceguys/addressing#95]
I was looking for a zone system for shipping purpose, when i found your other repo [commerceguys/zone](https://github.com/commerceguys/zone) that is now deprecated (at least that whats the readme tells) and a newer version of the zone functionality is included in this repo.

But for me it seems like the current implementation of zones is lacking a lot of things, like a scope (shipping or tax for most i guess) for each Zone. Also it seems like ZoneRepository and ZoneMatcher is not implemented in addressing repo?

At the same time i was also happy to see you had [commerceguys/tax](https://github.com/commerceguys/tax) since it was something that I would also need for the my project in future, but then it is also require the commerceguys/zone

Question is, did I totally missed something? Or should I just go for the older versions of all 3 instead of most recent version?

**Comment by bojanz** [comment]
commerceguys/tax hasn't been updated for addressing 1.x yet (which hasn't hit RC yet in any case).

What you're seeing is a general paradigm shift for these libraries, where we've given up on trying to provide entity interfaces for people. It was never truly useful, and every project has their own entity conventions that they want to follow. Instead, we let people define whatever entities they want, then  convert them to our value objects for passing to our services.

For zones that means that we don't care whether you have ShippingZone and TaxZone entities, or a single Zone entity with a scope property (or a Zone without a scope, if you don't care about shopping). That also saves you from having to override our ZoneRepository. Simply provide a toZone() or toValue() method on your entity that creates a Zone value object. You can then do $entity->toValue()->match().

Since we no longer have a ZoneRepository, we couldn't implement a ZoneMatcher, that is logic that needs to be reimplemented on your side. Our own usage of zones inside Drupal Commerce usually has them embedded inside a TaxType or a ShippingMethod, so we call ->match() directly and don't rely on a matcher service at all.
